;; neotree
(when (require 'neotree nil 'noerror)
  (global-set-key [f8] 'neotree-toggle)
  (setq neo-theme 'nerd)
  (setq neo-mode-line-type 'none)
  (setq neo-autorefresh t)
  (setq neo-window-width 35)
  (setq neo-smart-open t)
  (setq neo-show-updir-line nil)
  (setq neo-cwd-line-style 'button)
  (setq neo-toggle-window-keep-p t)
  (setq neo-hide-cursor t))
